import { createSlice, PayloadAction } from "@reduxjs/toolkit";
import { SongSlide } from "@/vmusic/ControlRoom/utils/lyricsParser";
import { createDisplaySequence } from "@/vmusic/ControlRoom/utils/displaySequence";

interface SongSlidesState {
  slides: SongSlide[];
  currentSlideId: string | null;
  currentDisplayIndex: number; // Index in display slides array (for chorus repetition)
  songTitle: string;
  isAutoGeneratedTitle: boolean; // true = auto-generated from paste, false = saved title
  currentSongId: string | null; // ID of the currently loaded song (null if pasted)
  isSaving: boolean;
  repeatChorusAfterVerse: boolean; // Setting to enable/disable chorus repetition
}

const initialState: SongSlidesState = {
  slides: [],
  currentSlideId: null,
  currentDisplayIndex: 0,
  songTitle: "",
  isAutoGeneratedTitle: true,
  currentSongId: null,
  isSaving: false,
  repeatChorusAfterVerse: true, // Enabled by default
};

const songSlidesSlice = createSlice({
  name: "songSlides",
  initialState,
  reducers: {
    setSlides: (state, action: PayloadAction<SongSlide[]>) => {
      state.slides = action.payload;
      // Auto-select first slide if slides exist
      if (action.payload.length > 0 && !state.currentSlideId) {
        state.currentSlideId = action.payload[0].id;
      }
      // Auto-generate title from first few words when new slides are pasted
      if (action.payload.length > 0) {
        const firstSlideContent = action.payload[0].content.trim();
        const firstWords = firstSlideContent.split(/\s+/).slice(0, 5).join(" ");
        state.songTitle =
          firstWords.length > 30
            ? firstWords.substring(0, 30) + "..."
            : firstWords;
        state.isAutoGeneratedTitle = true; // Mark as auto-generated
      }
      // Clear currentSongId when new slides are set (will be set by setCurrentSongId if loading)
      state.currentSongId = null;
    },
    setSongTitle: (state, action: PayloadAction<string>) => {
      state.songTitle = action.payload;
      state.isAutoGeneratedTitle = false; // Mark as saved/loaded title
    },
    setCurrentSongId: (state, action: PayloadAction<string | null>) => {
      state.currentSongId = action.payload;
    },
    setCurrentSlide: (state, action: PayloadAction<string>) => {
      console.log(
        `setCurrentSlide: payload=${action.payload.substring(
          0,
          30
        )}, currentDisplayIndex=${state.currentDisplayIndex}`
      );
      const wasAtDisplayIndex = state.currentDisplayIndex;
      state.currentSlideId = action.payload;

      // Only update display index if we're actually changing slides
      // Check if current display slide already matches this original ID
      const displaySlides = createDisplaySequence(
        state.slides,
        state.repeatChorusAfterVerse
      );
      const currentDisplaySlide = displaySlides[wasAtDisplayIndex];
      if (currentDisplaySlide) {
        const currentOriginalId = currentDisplaySlide.id.includes(
          "-repeat-after-v"
        )
          ? currentDisplaySlide.id.split("-repeat-after-v")[0]
          : currentDisplaySlide.id;

        // If we're already at a slide with this original ID, don't change display index
        if (currentOriginalId === action.payload) {
          console.log(
            `  Already at slide with this ID at position ${wasAtDisplayIndex}, keeping position`
          );
          return;
        }
      }

      // Find the new slide position
      const displayIndex = displaySlides.findIndex(
        (s) => s.id === action.payload
      );
      if (displayIndex !== -1) {
        console.log(`  Found exact match at display index ${displayIndex}`);
        state.currentDisplayIndex = displayIndex;
      } else {
        // Not found by exact ID match - find first occurrence of this original ID
        const index = displaySlides.findIndex((s) => {
          const originalId = s.id.includes("-repeat-after-v")
            ? s.id.split("-repeat-after-v")[0]
            : s.id;
          return originalId === action.payload;
        });
        console.log(`  Found by original ID at display index ${index}`);
        state.currentDisplayIndex = Math.max(0, index);
      }
    },
    setCurrentDisplayIndex: (state, action: PayloadAction<number>) => {
      console.log(`setCurrentDisplayIndex: ${action.payload}`);
      state.currentDisplayIndex = action.payload;
      // Also update currentSlideId to match the original slide at this display index
      const displaySlides = createDisplaySequence(
        state.slides,
        state.repeatChorusAfterVerse
      );
      const displaySlide = displaySlides[action.payload];
      if (displaySlide) {
        const originalId = displaySlide.id.includes("-repeat-after-v")
          ? displaySlide.id.split("-repeat-after-v")[0]
          : displaySlide.id;
        console.log(
          `  Setting currentSlideId to ${originalId.substring(0, 30)} (${
            displaySlide.type
          } - ${displaySlide.label})`
        );
        state.currentSlideId = originalId;
      }
    },
    setIsSaving: (state, action: PayloadAction<boolean>) => {
      state.isSaving = action.payload;
    },
    setRepeatChorusAfterVerse: (state, action: PayloadAction<boolean>) => {
      state.repeatChorusAfterVerse = action.payload;
    },
    clearSlides: (state) => {
      state.slides = [];
      state.currentSlideId = null;
      state.songTitle = "";
      state.isAutoGeneratedTitle = true;
      state.currentSongId = null;
    },
    addSlide: (state, action: PayloadAction<SongSlide>) => {
      state.slides.push(action.payload);
    },
    updateSlide: (
      state,
      action: PayloadAction<{ id: string; content: string }>
    ) => {
      const slide = state.slides.find((s) => s.id === action.payload.id);
      if (slide) {
        slide.content = action.payload.content;
      }
    },
    removeSlide: (state, action: PayloadAction<string>) => {
      state.slides = state.slides.filter((s) => s.id !== action.payload);
      // If removed slide was current, select first available
      if (state.currentSlideId === action.payload && state.slides.length > 0) {
        state.currentSlideId = state.slides[0].id;
      }
    },
    reorderSlides: (
      state,
      action: PayloadAction<{ fromIndex: number; toIndex: number }>
    ) => {
      const { fromIndex, toIndex } = action.payload;

      // Validate indices
      if (
        fromIndex < 0 ||
        fromIndex >= state.slides.length ||
        toIndex < 0 ||
        toIndex >= state.slides.length
      ) {
        return;
      }

      // Create a new array and move the slide
      const newSlides = [...state.slides];
      const [movedSlide] = newSlides.splice(fromIndex, 1);
      newSlides.splice(toIndex, 0, movedSlide);

      // Renumber slides by type
      // Chorus labels stay as "Chorus" but verses get renumbered
      const renumberedSlides = newSlides.map((slide, index) => {
        // Count how many slides of the same type come before this one
        const sameTypeBefore = newSlides
          .slice(0, index)
          .filter((s) => s.type === slide.type).length;

        const newNumber = sameTypeBefore + 1;

        // Format label based on type
        let newLabel: string;
        if (slide.type === "chorus") {
          // Chorus stays as just "Chorus" (no number for single chorus)
          // Or "Chorus 2" if multiple choruses exist
          const totalSameType = newSlides.filter(
            (s) => s.type === slide.type
          ).length;
          newLabel = totalSameType === 1 ? "Chorus" : `Chorus ${newNumber}`;
        } else {
          // Other types always show number
          newLabel = `${
            slide.type.charAt(0).toUpperCase() + slide.type.slice(1)
          } ${newNumber}`;
        }

        return {
          ...slide,
          number: newNumber,
          label: newLabel,
        };
      });

      state.slides = renumberedSlides;
    },
  },
});

export const {
  setSlides,
  setCurrentSlide,
  setCurrentDisplayIndex,
  setSongTitle,
  setCurrentSongId,
  setIsSaving,
  setRepeatChorusAfterVerse,
  clearSlides,
  addSlide,
  updateSlide,
  removeSlide,
  reorderSlides,
} = songSlidesSlice.actions;

// Selectors
export const selectDisplaySlides = (state: { songSlides: SongSlidesState }) => {
  const { slides, repeatChorusAfterVerse } = state.songSlides;
  return createDisplaySequence(slides, repeatChorusAfterVerse);
};

export default songSlidesSlice.reducer;
