import { useState, useEffect } from "react";
import { Minus, Maximize2, X, FileText, Home, User2 } from "lucide-react";

declare const __APP_VERSION__: string;
import UpdateManager from "./UpdateManager";
import { DepthButton, DepthSurface } from "./DepthButton";

import { useAppSelector, useAppDispatch } from "@/store";
import {
  setCurrentScreen,
  setTheme,
  minimizeApp,
  maximizeApp,
  closeApp,
} from "@/store/slices/appSlice";
import { ThemeToggle } from "./ThemeToggler";
import { useTheme } from "@/Provider/Theme";

const TitleBar = () => {
  const dispatch = useAppDispatch();
  const currentScreen = useAppSelector((state) => state.app.currentScreen);
  const songTitle = useAppSelector((state) => state.songSlides.songTitle);
  const isAutoGeneratedTitle = useAppSelector(
    (state) => state.songSlides.isAutoGeneratedTitle,
  );
  const currentSlideId = useAppSelector(
    (state) => state.songSlides.currentSlideId,
  );
  const slides = useAppSelector((state) => state.songSlides.slides);
  const { isDarkMode } = useTheme();

  const currentSlide = slides.find((slide) => slide.id === currentSlideId);

  const displayTitle =
    !isAutoGeneratedTitle && songTitle && songTitle.trim() !== ""
      ? songTitle
      : null;

  const shouldHideTitleBar = window.location.hash.includes(
    "presentation-display",
  );
  if (shouldHideTitleBar) return null;

  useEffect(() => {
    const savedTheme = localStorage.getItem("bmusictheme");
    if (savedTheme) dispatch(setTheme(savedTheme as any));
  }, [dispatch]);

  const handleMinimize = () => dispatch(minimizeApp());
  const handleMaximize = () => dispatch(maximizeApp());
  const handleClose = () => dispatch(closeApp());

  const selectedBg = isDarkMode ? "url('./wood10.jpg')" : "url(./wood10.jpg)";

  const titlebarInactiveTextClass = isDarkMode
    ? "text-white/80 border-white/25 hover:text-white"
    : "text-black/80 border-black/25 hover:text-black";
  const titlebarActiveTextClass = isDarkMode
    ? "text-white border-white/45"
    : "text-black border-black/40";
  return (
    <div
      className="h-7 w-full fixed flex z-50 top-0 m-auto select-none"
      style={
        {
          WebkitAppRegion: "drag",
          backgroundImage: !isDarkMode
            ? `linear-gradient(to bottom,
             rgba(255, 255, 255, 0%) 0%,
             rgba(160, 160, 160, 1) 100%),
             ${selectedBg}`
            : `linear-gradient(to bottom,
             rgba(44, 44, 44, 0) 0%,
             #1c1c1c 80%),
              ${selectedBg}`,
          backgroundRepeat: "repeat",
          backgroundSize: !isDarkMode ? "30px" : "20px",
          backdropFilter: "blur(10px)",
          zIndex: 10,
        } as any
      }
    >
      <div className="flex w-full items-center justify-center px-1">
        <div
          className="flex items-center justify-between w-full"
          style={{ WebkitAppRegion: "no-drag" } as any}
        >
          <div className="flex items-center gap-1">
            <img src="./evsongsicon.png" alt="icon" className="w-5 h-5 mr-1" />

            <DepthButton
              onClick={() => dispatch(setCurrentScreen("Home"))}
              sizeClassName="w-6 h-6 rounded-full"
              className={currentScreen === "Songs" ? "" : "hidden"}
              inactiveClassName={titlebarInactiveTextClass}
              inactiveSurfaceClassName="bg-gradient-to-br from-white/20 via-white/15 to-white/10 group-hover:from-white/30 group-hover:via-white/20 group-hover:to-white/15"
              title="Home"
            >
              <Home className="w-4 h-4" />
            </DepthButton>

            <DepthButton
              onClick={() => dispatch(setCurrentScreen("userguide"))}
              sizeClassName="w-6 h-6 rounded-full"
              className={currentScreen !== "Songs" ? "hidden" : ""}
              active={currentScreen === "userguide"}
              inactiveClassName={titlebarInactiveTextClass}
              activeClassName={titlebarActiveTextClass}
              inactiveSurfaceClassName="bg-gradient-to-br from-white/20 via-white/15 to-white/10 group-hover:from-white/30 group-hover:via-white/20 group-hover:to-white/15"
              activeSurfaceClassName="bg-gradient-to-br from-white/35 via-white/25 to-white/20"
              title="User guide"
            >
              <User2 className="w-4 h-4" />
            </DepthButton>

            <ThemeToggle />

            {currentScreen === "Songs" && (displayTitle || currentSlide) && (
              <div className="flex items-center gap-1.5 ml-1">
                {displayTitle && (
                  <DepthSurface className="flex items-center gap-1.5 px-2 py-0.5 rounded-full">
                    <FileText className="w-3 h-3 text-white/75 flex-shrink-0" />
                    <span className="text-[11px] font-medium text-white/90 max-w-[180px] truncate">
                      {displayTitle}
                    </span>
                  </DepthSurface>
                )}
                {currentSlide && (
                  <DepthSurface className="px-2 py-0.5 rounded-full">
                    <span className="text-[11px] font-semibold text-white/95">
                      {currentSlide.label}
                    </span>
                  </DepthSurface>
                )}
              </div>
            )}
          </div>

          <div className="flex items-center gap-1 mr-1">
            <UpdateManager />
            <div className="w-px h-3.5 bg-white/15 mx-0.5" />
            <DepthButton
              onClick={handleMinimize}
              sizeClassName="w-10 h-6 rounded"
              inactiveClassName={titlebarInactiveTextClass}
              inactiveSurfaceClassName="bg-gradient-to-br from-white/20 via-white/15 to-white/10 group-hover:from-white/30 group-hover:via-white/20 group-hover:to-white/15"
              title="Minimize"
            >
              <Minus className="w-3.5 h-3.5" strokeWidth={3} />
            </DepthButton>
            <DepthButton
              onClick={handleMaximize}
              sizeClassName="w-10 h-6 rounded"
              inactiveClassName={titlebarInactiveTextClass}
              inactiveSurfaceClassName="bg-gradient-to-br from-white/20 via-white/15 to-white/10 group-hover:from-white/30 group-hover:via-white/20 group-hover:to-white/15"
              title="Maximize"
            >
              <Maximize2 className="w-3 h-3" strokeWidth={2} />
            </DepthButton>
            <DepthButton
              onClick={handleClose}
              sizeClassName="w-10 h-6 rounded "
              inactiveClassName="text-black dark:text-white/90 border-yellow-500/70 hover:text-white"
              inactiveSurfaceClassName="bg-gradient-to-br from-yellow-500 via-yellow-500 to-yellow-600 group-hover:from-yellow-500 group-hover:via-yellow-600 group-hover:to-yellow-600"
              title="Close"
            >
              <X className="w-3.5 h-3.5 text-black dark:text-white/90" strokeWidth={3} />
            </DepthButton>
          </div>
        </div>
      </div>
    </div>
  );
};

export default TitleBar;
