// TitleBar.tsx — Unified Antigravity-style Desktop TitleBar & Command Bar
import React, { useState, useEffect, useRef } from "react";
import {
  Minus,
  Square,
  Copy,
  X,
  Check,
  FileText,
  Home,
  User2,
  Plus,
  Edit3,
  Trash2,
  RefreshCw,
  Folder,
  Radio,
  ChevronDown,
  Printer,
  Save,
  Settings,
  Monitor,
  MonitorStop,
  MonitorCheck,
  BellPlus,
  Sheet,
  Music,
  BarChart3,
  NotebookPen,
  FilePlus2,
  Layers,
  Sliders,
  LoaderCircle,
} from "lucide-react";
import { Tooltip } from "antd";
import UpdateManager from "./UpdateManager";
import { ThemeToggle } from "./ThemeToggler";
import { DepthButton, DepthSurface } from "./DepthButton";
import { SearchWithDropdown } from "../vmusic/ControlRoom/ActionBar/SearchWithDropdown";
import BackupNotification from "../vmusic/ControlRoom/components/BackupNotification";
import { GamyCard } from "../vmusic/shared/GamyCard";
import { Song } from "@/types";
import { useTheme } from "@/Provider/Theme";
import { useAppSelector, useAppDispatch } from "@/store";
import {
  setCurrentScreen,
  setTheme,
  minimizeApp,
  maximizeApp,
  closeApp,
} from "@/store/slices/appSlice";
import {
  openDeleteConfirmModal,
  toggleSettings,
  toggleStatistics,
  toggleAllSongsView,
  setRightPanelView,
  setIsEditingSlide,
  setShowAddSlideDialog,
  setShowTitleDialog,
  toggleSongEditor,
  toggleNewSongModal,
  closeSongEditor,
  closeNewSongModal,
} from "@/store/slices/uiSlice";
import { setSongRepo, updateSong } from "@/store/slices/songSlice";
import { setFontFamily } from "@/store/slices/projectionSlice";
import { addProjectionEntry } from "@/store/slices/projectionHistorySlice";
import { recordProjection } from "@/store/slices/statisticsSlice";
import { encodeSongData, validateSongForSave } from "../vmusic/ControlRoom/utils/songFileFormat";

declare const __APP_VERSION__: string;

export interface TitleBarProps {
  isDarkMode?: boolean;
  selectedSong?: Song | null;
  searchQuery?: string;
  isProjectionActive?: boolean;
  songs?: Song[];
  showDeleteConfirmation?: () => void;
  loadSongs?: () => void;
  changeDirectory?: () => void;
  updateSearchQuery?: (query: string) => void;
  presentSong?: (song: Song) => void;
  addToast?: (
    message: string,
    type: "success" | "error" | "warning" | "info",
  ) => void;
  onRequestDelete?: () => void;
  onSelectSongFromSearch?: (song: Song) => void;
}

const TitleBar: React.FC<TitleBarProps> = ({
  selectedSong = null,
  searchQuery = "",
  isProjectionActive = false,
  songs = [],
  showDeleteConfirmation = () => {},
  loadSongs = () => {},
  changeDirectory = () => {},
  updateSearchQuery = () => {},
  presentSong = () => {},
  addToast = () => {},
  onRequestDelete = () => {},
  onSelectSongFromSearch = () => {},
}) => {
  const dispatch = useAppDispatch();
  const { isDarkMode } = useTheme();
  // Icon stroke weight: lighter in light mode (less harsh on gray bg), heavier in dark
  const sw = isDarkMode ? 3.5 : 2.5;
  const [isWindowMaximized, setIsWindowMaximized] = useState(false);

  // Active dropdown menu: 'File' | 'Edit' | 'View' | 'Projection' | 'Help' | null
  const [activeMenu, setActiveMenu] = useState<string | null>(null);
  const menuBarRef = useRef<HTMLDivElement>(null);

  // Redux states
  const currentScreen = useAppSelector((state) => state.app.currentScreen);
  const { slides, isSaving, currentSlideId, currentSongId, songTitle, isAutoGeneratedTitle } =
    useAppSelector((state) => state.songSlides);
  const songRepo = useAppSelector((state) => state.songs.songRepo);
  const { rightPanelView, isEditingSlide, showSongEditor, showNewSongModal } =
    useAppSelector((state) => state.ui);

  const currentSlide = slides.find((slide) => slide.id === currentSlideId);
  const currentSong = songs.find((song) => song.id === currentSongId);
  const displayTitle =
    !isAutoGeneratedTitle && songTitle && songTitle.trim() !== ""
      ? songTitle
      : null;

  // System font selector state
  const [systemFonts, setSystemFonts] = useState<string[]>([]);
  const [fontsLoading, setFontsLoading] = useState(true);
  const [selectedFont, setSelectedFont] = useState("Arial");
  const [showFontDropdown, setShowFontDropdown] = useState(false);
  const [fontSearchQuery, setFontSearchQuery] = useState("");
  const [fontListScrollTop, setFontListScrollTop] = useState(0);

  const fontListRef = useRef<HTMLDivElement>(null);
  const fontDropdownRef = useRef<HTMLDivElement>(null);
  const fontSearchInputRef = useRef<HTMLInputElement>(null);

  const FONT_ITEM_HEIGHT = 28;
  const FONT_LIST_HEIGHT = 400;
  const OVERSCAN = 3;

  // Do not render on projection display window
  const shouldHideTitleBar = window.location.hash.includes("presentation-display");
  if (shouldHideTitleBar) return null;

  // Load saved theme
  useEffect(() => {
    const savedTheme = localStorage.getItem("bmusictheme");
    if (savedTheme) dispatch(setTheme(savedTheme as any));
  }, [dispatch]);

  // Window maximized state tracking
  useEffect(() => {
    let isMounted = true;
    window.api?.isAppWindowMaximized?.().then((maximized) => {
      if (isMounted) setIsWindowMaximized(maximized);
    });

    const cleanup = window.api?.onWindowMaximizedChanged?.((maximized) => {
      setIsWindowMaximized(maximized);
    });

    return () => {
      isMounted = false;
      cleanup?.();
    };
  }, []);

  // Load system fonts on mount
  useEffect(() => {
    const loadFonts = async () => {
      setFontsLoading(true);
      try {
        const fonts = await window.api.getSystemFonts();
        setSystemFonts(fonts);
        const savedFont = localStorage.getItem("bmusicfontFamily");
        if (savedFont) {
          setSelectedFont(savedFont);
        } else if (fonts.length > 0 && !selectedFont) {
          setSelectedFont(fonts[0]);
        }
      } catch (error) {
        setSystemFonts([
          "Arial",
          "Calibri",
          "Cambria",
          "Comic Sans MS",
          "Courier New",
          "Georgia",
          "Impact",
          "Segoe UI",
          "Tahoma",
          "Times New Roman",
          "Verdana",
        ]);
      } finally {
        setFontsLoading(false);
      }
    };
    loadFonts();
  }, []);

  // Close menus & dropdowns when clicking outside
  useEffect(() => {
    const handleClickOutside = (event: MouseEvent) => {
      const target = event.target as Node;
      if (menuBarRef.current && !menuBarRef.current.contains(target)) {
        setActiveMenu(null);
      }
      if (fontDropdownRef.current && !fontDropdownRef.current.contains(target)) {
        setShowFontDropdown(false);
      }
    };

    document.addEventListener("mousedown", handleClickOutside);
    return () => document.removeEventListener("mousedown", handleClickOutside);
  }, []);

  // Filter fonts
  const filteredFonts = systemFonts.filter((font) =>
    font.toLowerCase().includes(fontSearchQuery.toLowerCase()),
  );

  const getProjectionStatsSongId = (title: string) => {
    if (currentSong?.id) return currentSong.id;
    if (currentSongId) return currentSongId;
    const normalizedTitle = title.trim().toLowerCase().replace(/\s+/g, "-");
    return `unsaved-${normalizedTitle || "untitled"}`;
  };

  const prelistedSongs = songs.filter((song) => song.isPrelisted);
  const allSongs = songs;

  // PDF generation handlers
  const handlePrintPrelistToPDF = async () => {
    try {
      const { generatePrelistPDF } = await import("@/utils/pdfGenerator");
      await generatePrelistPDF(prelistedSongs);
      addToast(`Prelist PDF generated successfully!`, "success");
    } catch (error) {
      addToast(error instanceof Error ? error.message : "Failed to generate prelist PDF", "error");
    }
  };

  const handlePrintAllSongsToPDF = async () => {
    try {
      const { generateSongsDatabasePDF } = await import("@/utils/pdfGenerator");
      await generateSongsDatabasePDF(allSongs);
      addToast(`Songs database PDF generated successfully!`, "success");
    } catch (error) {
      addToast(error instanceof Error ? error.message : "Failed to generate songs database PDF", "error");
    }
  };

  // Save current song handler
  const handleSaveClick = () => {
    if (slides.length === 0) {
      addToast("No slides to save. Paste lyrics first.", "warning");
      return;
    }
    dispatch(setShowTitleDialog(true));
  };

  // Save to prelist
  const handleSaveToPrelist = async () => {
    const song = currentSongId
      ? songs.find((s) => s.id === currentSongId)
      : selectedSong
        ? songs.find((s) => s.id === selectedSong.id)
        : null;

    const title = songTitle || song?.title || selectedSong?.title || "";
    const language = song?.language || selectedSong?.language || "English";

    if (slides.length === 0) {
      addToast("No slides to add to prelist. Paste lyrics first.", "warning");
      return;
    }

    if (!title.trim()) {
      addToast("Select a song before adding it to prelist.", "warning");
      return;
    }

    const validation = validateSongForSave(title, slides);
    if (!validation.valid) {
      addToast(validation.error || "Invalid song data", "error");
      return;
    }

    try {
      const now = new Date().toISOString();
      const createdAt: string = song?.metadata?.created ?? now;
      const encodedContent = encodeSongData(title, slides, true, undefined, language);
      const result = await window.api.saveSong("", title, encodedContent);

      if (currentSongId || song?.id) {
        const updatedSong: Song = {
          id: currentSongId || song!.id,
          title: result.sanitizedTitle || title,
          path: result.filePath || song?.path || "",
          content: encodedContent,
          categories: song?.categories || [],
          dateModified: new Date().toISOString(),
          size: encodedContent.length,
          isPrelisted: true,
          language,
          metadata: {
            created: createdAt,
            modified: now,
            isPrelisted: true,
            language,
          },
        };
        dispatch(updateSong(updatedSong));
        dispatch({ type: "songs/setSelectedSong", payload: updatedSong });
      }

      addToast(`"${title}" added to prelist! 🎵`, "success");
      loadSongs();
      window.dispatchEvent(new CustomEvent("queueflow:action", { detail: { type: "refresh" } }));
    } catch (error) {
      addToast("Failed to add to prelist. Please try again.", "error");
    }
  };

  // Projection Toggle
  const handleProjectionToggle = async () => {
    try {
      if (isProjectionActive) {
        await window.api.closeProjectionWindow();
        addToast("Projection closed", "info");
      } else {
        if (slides.length === 0) {
          addToast("No slides to project. Paste lyrics first.", "warning");
          return;
        }

        const songData = {
          title: songTitle || currentSong?.title || "Untitled Song",
          content: "",
          slides: slides.map((slide) => ({
            content: slide.content,
            type: slide.type,
            number: slide.number,
          })),
        };

        await window.api.projectSong(songData);

        const projectedTitle = songTitle || currentSong?.title || "Untitled Song";
        const projectedAt = Date.now();
        const projectionSongId = getProjectionStatsSongId(projectedTitle);

        dispatch(addProjectionEntry({ songId: projectionSongId, songTitle: projectedTitle }));
        dispatch(recordProjection({ songId: projectionSongId, songTitle: projectedTitle, projectedAt }));

        setTimeout(async () => {
          if (slides.length > 0 && currentSlideId) {
            const currentIndex = slides.findIndex((s) => s.id === currentSlideId);
            const slide = slides[currentIndex] || slides[0];

            const slideData = {
              type: "SLIDE_UPDATE",
              slide: {
                content: slide.content,
                type: slide.type,
                number: slide.number,
              },
              songTitle: songTitle || currentSong?.title || "Untitled Song",
              currentIndex: Math.max(0, currentIndex),
              totalSlides: slides.length,
              backgroundColor: "#000000",
              slides: slides.map((s) => ({
                content: s.content,
                type: s.type,
                number: s.number,
              })),
            };

            await window.api.sendToSongProjection(slideData);
          }
        }, 500);

        addToast("Projection started", "success");
      }
    } catch (error) {
      addToast(`Failed to ${isProjectionActive ? "close" : "start"} projection`, "error");
    }
  };

  // Window controls
  const handleMinimize = () => dispatch(minimizeApp());
  const handleMaximize = () => dispatch(maximizeApp());
  const handleClose = () => dispatch(closeApp());

  // Resolve to main workspace from any view
  const handleResolveToWorkspace = () => {
    dispatch(setCurrentScreen("Songs"));
    dispatch(setRightPanelView("bento"));
    dispatch(setIsEditingSlide(false));
    dispatch(closeSongEditor());
    dispatch(closeNewSongModal());
  };

  const isSongsScreen = currentScreen === "Songs";

  return (
    <div
      className="h-9 w-full fixed top-0 left-0 right-0 z-50 flex items-center justify-between px-2 select-none border-b text-xs transition-colors duration-200"
      style={{ background: 'var(--tb-bg)', borderBottomWidth: '1px', borderBottomStyle: 'solid', borderBottomColor: 'var(--tb-border)', color: 'var(--tb-text)', WebkitAppRegion: 'drag' } as React.CSSProperties}
    >
      {/* ─── LEFT: Logo, Desktop Menus, Quick Action Tools ─── */}
      <div
        className="flex items-center gap-1 flex-shrink-0"
        style={{ WebkitAppRegion: "no-drag" } as React.CSSProperties}
      >
        {/* App Logo */}
        <div
          className="flex items-center gap-1.5 mr-1 cursor-pointer"
          onClick={() => dispatch(setCurrentScreen("Home"))}
          title="songCast"
        >
          <img src="./evsongsicon.png" alt="icon" className="w-4 h-4 object-contain" />
        </div>

        {/* Desktop Menu Bar (File, Edit, View, Projection, Help) */}
        <div className="flex items-center gap-0.5 relative" ref={menuBarRef}>
          {/* FILE MENU */}
          <div className="relative">
            <button
              onClick={() => setActiveMenu(activeMenu === "File" ? null : "File")}
              onMouseEnter={() => activeMenu && setActiveMenu("File")}
              className="px-2 py-0.5 rounded text-[11px] font-medium transition-colors"
              style={activeMenu === "File" ? { background: 'var(--tb-active-bg)', color: 'var(--tb-text)' } : { color: 'var(--tb-text-muted)' } as React.CSSProperties}
              onMouseLeave={(e) => { if (activeMenu !== 'File') { (e.currentTarget as HTMLButtonElement).style.background = ''; (e.currentTarget as HTMLButtonElement).style.color = 'var(--tb-text-muted)'; } }}
            >
              File
            </button>
            {activeMenu === "File" && (
              <div className="absolute top-full left-0 mt-1 w-52 rounded-md shadow-2xl py-1 z-[99999] text-[11px]" style={{ background: 'var(--tb-dropdown-bg)', border: '1px solid var(--tb-dropdown-border)', color: 'var(--tb-text)' } as React.CSSProperties}>
                <button
                  onClick={() => {
                    dispatch(toggleNewSongModal());
                    setActiveMenu(null);
                  }}
                  className="w-full flex items-center justify-between px-3 py-1.5 text-left transition-colors hover:bg-[var(--tb-dropdown-hover-bg)] hover:text-[var(--tb-dropdown-hover-text)]"
                >
                  <span className="flex items-center gap-2">
                    <FilePlus2 className="w-3.5 h-3.5" />
                    New Song
                  </span>
                  <span className="text-[10px] opacity-40">Ctrl+N</span>
                </button>
                <button
                  onClick={() => {
                    handleSaveClick();
                    setActiveMenu(null);
                  }}
                  disabled={slides.length === 0 || isSaving}
                  className="w-full flex items-center justify-between px-3 py-1.5 text-left transition-colors hover:bg-[var(--tb-dropdown-hover-bg)] hover:text-[var(--tb-dropdown-hover-text)] disabled:opacity-40 disabled:hover:bg-transparent"
                >
                  <span className="flex items-center gap-2">
                    <Save className="w-3.5 h-3.5" />
                    Save Song
                  </span>
                  <span className="text-[10px] opacity-40">Ctrl+S</span>
                </button>
                <div className="h-px my-1" style={{ background: 'var(--tb-dropdown-border)' }} />
                <button
                  onClick={() => {
                    changeDirectory();
                    setActiveMenu(null);
                  }}
                  className="w-full flex items-center gap-2 px-3 py-1.5 text-left transition-colors hover:bg-[var(--tb-dropdown-hover-bg)] hover:text-[var(--tb-dropdown-hover-text)]"
                >
                  <Folder className="w-3.5 h-3.5" />
                  Choose Songs Directory...
                </button>
                <button
                  onClick={() => {
                    dispatch(setSongRepo(""));
                    localStorage.removeItem("bmusicsongdir");
                    addToast("Songs directory cleared", "info");
                    setActiveMenu(null);
                  }}
                  disabled={!songRepo || songRepo.trim() === ""}
                  className="w-full flex items-center gap-2 px-3 py-1.5 text-left text-red-500 hover:bg-[var(--tb-dropdown-hover-bg)] hover:text-red-400 disabled:opacity-40 disabled:hover:bg-transparent transition-colors"
                >
                  <X className="w-3.5 h-3.5" />
                  Clear Directory
                </button>
                <div className="h-px my-1" style={{ background: 'var(--tb-dropdown-border)' }} />
                <button
                  onClick={() => {
                    handlePrintPrelistToPDF();
                    setActiveMenu(null);
                  }}
                  disabled={prelistedSongs.length === 0}
                  className="w-full flex items-center gap-2 px-3 py-1.5 text-left transition-colors hover:bg-[var(--tb-dropdown-hover-bg)] hover:text-[var(--tb-dropdown-hover-text)] disabled:opacity-40 disabled:hover:bg-transparent"
                >
                  <Sheet className="w-3.5 h-3.5" />
                  Export Prelist to PDF
                </button>
                <button
                  onClick={() => {
                    handlePrintAllSongsToPDF();
                    setActiveMenu(null);
                  }}
                  disabled={allSongs.length === 0}
                  className="w-full flex items-center gap-2 px-3 py-1.5 text-left transition-colors hover:bg-[var(--tb-dropdown-hover-bg)] hover:text-[var(--tb-dropdown-hover-text)] disabled:opacity-40 disabled:hover:bg-transparent"
                >
                  <Printer className="w-3.5 h-3.5" />
                  Export All Songs to PDF
                </button>
              </div>
            )}
          </div>

          {/* EDIT MENU */}
          <div className="relative">
            <button
              onClick={() => setActiveMenu(activeMenu === "Edit" ? null : "Edit")}
              onMouseEnter={() => activeMenu && setActiveMenu("Edit")}
              className="px-2 py-0.5 rounded text-[11px] font-medium transition-colors"
              style={activeMenu === "Edit" ? { background: 'var(--tb-active-bg)', color: 'var(--tb-text)' } : { color: 'var(--tb-text-muted)' } as React.CSSProperties}
            >
              Edit
            </button>
            {activeMenu === "Edit" && (
              <div className="absolute top-full left-0 mt-1 w-52 rounded-md shadow-2xl py-1 z-[99999] text-[11px]" style={{ background: 'var(--tb-dropdown-bg)', border: '1px solid var(--tb-dropdown-border)', color: 'var(--tb-text)' } as React.CSSProperties}>
                <button
                  onClick={() => {
                    dispatch(setIsEditingSlide(true));
                    setActiveMenu(null);
                  }}
                  disabled={currentSlideId === null}
                  className="w-full flex items-center gap-2 px-3 py-1.5 text-left transition-colors hover:bg-[var(--tb-dropdown-hover-bg)] hover:text-[var(--tb-dropdown-hover-text)] disabled:opacity-40 disabled:hover:bg-transparent"
                >
                  <Edit3 className="w-3.5 h-3.5" />
                  Edit Current Slide
                </button>
                <button
                  onClick={() => {
                    dispatch(toggleSongEditor());
                    setActiveMenu(null);
                  }}
                  disabled={slides.length === 0}
                  className="w-full flex items-center gap-2 px-3 py-1.5 text-left transition-colors hover:bg-[var(--tb-dropdown-hover-bg)] hover:text-[var(--tb-dropdown-hover-text)] disabled:opacity-40 disabled:hover:bg-transparent"
                >
                  <NotebookPen className="w-3.5 h-3.5" />
                  Edit Full Song
                </button>
                <button
                  onClick={() => {
                    dispatch(setShowAddSlideDialog(true));
                    setActiveMenu(null);
                  }}
                  className="w-full flex items-center gap-2 px-3 py-1.5 text-left transition-colors hover:bg-[var(--tb-dropdown-hover-bg)] hover:text-[var(--tb-dropdown-hover-text)]"
                >
                  <Plus className="w-3.5 h-3.5" />
                  Add New Slide
                </button>
                <div className="h-px my-1" style={{ background: 'var(--tb-dropdown-border)' }} />
                <button
                  onClick={() => {
                    if (isEditingSlide) {
                      onRequestDelete();
                    } else if (currentSong) {
                      dispatch(openDeleteConfirmModal({ song: currentSong, type: "permanent" }));
                    }
                    setActiveMenu(null);
                  }}
                  disabled={isEditingSlide ? currentSlideId === null : !currentSong}
                  className="w-full flex items-center justify-between px-3 py-1.5 text-left text-red-500 hover:bg-[var(--tb-dropdown-hover-bg)] hover:text-red-400 disabled:opacity-40 disabled:hover:bg-transparent transition-colors"
                >
                  <span className="flex items-center gap-2">
                    <Trash2 className="w-3.5 h-3.5" />
                    {isEditingSlide ? "Delete Current Slide" : "Delete Selected Song"}
                  </span>
                  <span className="text-[10px] opacity-40">Del</span>
                </button>
              </div>
            )}
          </div>

          {/* VIEW MENU */}
          <div className="relative">
            <button
              onClick={() => setActiveMenu(activeMenu === "View" ? null : "View")}
              onMouseEnter={() => activeMenu && setActiveMenu("View")}
              className="px-2 py-0.5 rounded text-[11px] font-medium transition-colors"
              style={activeMenu === "View" ? { background: 'var(--tb-active-bg)', color: 'var(--tb-text)' } : { color: 'var(--tb-text-muted)' } as React.CSSProperties}
            >
              View
            </button>
            {activeMenu === "View" && (
              <div className="absolute top-full left-0 mt-1 w-52 rounded-md shadow-2xl py-1 z-[99999] text-[11px]" style={{ background: 'var(--tb-dropdown-bg)', border: '1px solid var(--tb-dropdown-border)', color: 'var(--tb-text)' } as React.CSSProperties}>
                <button
                  onClick={() => {
                    dispatch(setCurrentScreen("Songs"));
                    dispatch(setRightPanelView("bento"));
                    setActiveMenu(null);
                  }}
                  className="w-full flex items-center justify-between px-3 py-1.5 text-left transition-colors hover:bg-[var(--tb-dropdown-hover-bg)] hover:text-[var(--tb-dropdown-hover-text)]"
                >
                  <span className="flex items-center gap-2">
                    <Layers className="w-3.5 h-3.5" />
                    Songs Control Room
                  </span>
                  <span className="text-[10px] opacity-40">Ctrl+S</span>
                </button>
                <button
                  onClick={() => {
                    dispatch(toggleAllSongsView());
                    setActiveMenu(null);
                  }}
                  className="w-full flex items-center gap-2 px-3 py-1.5 text-left transition-colors hover:bg-[var(--tb-dropdown-hover-bg)] hover:text-[var(--tb-dropdown-hover-text)]"
                >
                  <Music className="w-3.5 h-3.5" />
                  Browse All Songs
                </button>
                <button
                  onClick={() => {
                    dispatch(setCurrentScreen("Home"));
                    setActiveMenu(null);
                  }}
                  className="w-full flex items-center justify-between px-3 py-1.5 text-left transition-colors hover:bg-[var(--tb-dropdown-hover-bg)] hover:text-[var(--tb-dropdown-hover-text)]"
                >
                  <span className="flex items-center gap-2">
                    <Home className="w-3.5 h-3.5" />
                    Home / Workspace
                  </span>
                  <span className="text-[10px] opacity-40">Ctrl+H</span>
                </button>
                <div className="h-px my-1" style={{ background: 'var(--tb-dropdown-border)' }} />
                <button
                  onClick={() => {
                    dispatch(toggleSettings());
                    setActiveMenu(null);
                  }}
                  className="w-full flex items-center gap-2 px-3 py-1.5 text-left transition-colors hover:bg-[var(--tb-dropdown-hover-bg)] hover:text-[var(--tb-dropdown-hover-text)]"
                >
                  <Settings className="w-3.5 h-3.5" />
                  Settings
                </button>
                <button
                  onClick={() => {
                    dispatch(toggleStatistics());
                    setActiveMenu(null);
                  }}
                  className="w-full flex items-center gap-2 px-3 py-1.5 text-left transition-colors hover:bg-[var(--tb-dropdown-hover-bg)] hover:text-[var(--tb-dropdown-hover-text)]"
                >
                  <BarChart3 className="w-3.5 h-3.5" />
                  Statistics &amp; History
                </button>
              </div>
            )}
          </div>

          {/* PROJECTION MENU */}
          <div className="relative">
            <button
              onClick={() => setActiveMenu(activeMenu === "Projection" ? null : "Projection")}
              onMouseEnter={() => activeMenu && setActiveMenu("Projection")}
              className="px-2 py-0.5 rounded text-[11px] font-medium transition-colors"
              style={activeMenu === "Projection" ? { background: 'var(--tb-active-bg)', color: 'var(--tb-text)' } : { color: 'var(--tb-text-muted)' } as React.CSSProperties}
            >
              Projection
            </button>
            {activeMenu === "Projection" && (
              <div className="absolute top-full left-0 mt-1 w-56 rounded-md shadow-2xl py-1 z-[99999] text-[11px]" style={{ background: 'var(--tb-dropdown-bg)', border: '1px solid var(--tb-dropdown-border)', color: 'var(--tb-text)' } as React.CSSProperties}>
                <button
                  onClick={() => {
                    handleProjectionToggle();
                    setActiveMenu(null);
                  }}
                  disabled={!isProjectionActive && slides.length === 0}
                  className="w-full flex items-center gap-2 px-3 py-1.5 text-left transition-colors hover:bg-[var(--tb-dropdown-hover-bg)] hover:text-[var(--tb-dropdown-hover-text)] disabled:opacity-40 disabled:hover:bg-transparent"
                >
                  {isProjectionActive ? (
                    <>
                      <MonitorStop className="w-3.5 h-3.5 text-red-400" />
                      Stop Projection
                    </>
                  ) : (
                    <>
                      <Monitor className="w-3.5 h-3.5 text-green-400" />
                      Start Projection
                    </>
                  )}
                </button>
                {isProjectionActive && (
                  <button
                    onClick={async () => {
                      try {
                        await window.api.focusProjectionWindow();
                      } catch {
                        addToast("Could not focus projection window", "error");
                      }
                      setActiveMenu(null);
                    }}
                    className="w-full flex items-center justify-between px-3 py-1.5 text-left transition-colors hover:bg-[var(--tb-dropdown-hover-bg)] hover:text-[var(--tb-dropdown-hover-text)]"
                  >
                    <span className="flex items-center gap-2">
                      <MonitorCheck className="w-3.5 h-3.5 text-blue-400" />
                      Focus Projection Window
                    </span>
                    <span className="text-[10px] opacity-40">Shift+F</span>
                  </button>
                )}
                <button
                  onClick={() => {
                    if (selectedSong) presentSong(selectedSong);
                    setActiveMenu(null);
                  }}
                  disabled={!selectedSong}
                  className="w-full flex items-center gap-2 px-3 py-1.5 text-left transition-colors hover:bg-[var(--tb-dropdown-hover-bg)] hover:text-[var(--tb-dropdown-hover-text)] disabled:opacity-40 disabled:hover:bg-transparent"
                >
                  <Radio className={`w-3.5 h-3.5 ${isDarkMode ? "text-blue-400" : "text-blue-900"}`} />
                  Present Selected Song Live
                </button>
                <div className="h-px my-1" style={{ background: 'var(--tb-dropdown-border)' }} />
                <button
                  onClick={() => {
                    loadSongs();
                    setActiveMenu(null);
                  }}
                  className="w-full flex items-center gap-2 px-3 py-1.5 text-left transition-colors hover:bg-[var(--tb-dropdown-hover-bg)] hover:text-[var(--tb-dropdown-hover-text)]"
                >
                  <RefreshCw className="w-3.5 h-3.5" />
                  Refresh Songs List
                </button>
              </div>
            )}
          </div>

          {/* HELP MENU */}
          <div className="relative">
            <button
              onClick={() => setActiveMenu(activeMenu === "Help" ? null : "Help")}
              onMouseEnter={() => activeMenu && setActiveMenu("Help")}
              className="px-2 py-0.5 rounded text-[11px] font-medium transition-colors"
              style={activeMenu === "Help" ? { background: 'var(--tb-active-bg)', color: 'var(--tb-text)' } : { color: 'var(--tb-text-muted)' } as React.CSSProperties}
            >
              Help
            </button>
            {activeMenu === "Help" && (
              <div className="absolute top-full left-0 mt-1 w-48 rounded-md shadow-2xl py-1 z-[99999] text-[11px]" style={{ background: 'var(--tb-dropdown-bg)', border: '1px solid var(--tb-dropdown-border)', color: 'var(--tb-text)' } as React.CSSProperties}>
                <button
                  onClick={() => {
                    dispatch(setCurrentScreen("userguide"));
                    setActiveMenu(null);
                  }}
                  className="w-full flex items-center gap-2 px-3 py-1.5 text-left transition-colors hover:bg-[var(--tb-dropdown-hover-bg)] hover:text-[var(--tb-dropdown-hover-text)]"
                >
                  <User2 className="w-3.5 h-3.5" />
                  User Guide
                </button>
                <button
                  onClick={() => {
                    dispatch(setCurrentScreen("Home"));
                    setActiveMenu(null);
                  }}
                  className="w-full flex items-center gap-2 px-3 py-1.5 text-left transition-colors hover:bg-[var(--tb-dropdown-hover-bg)] hover:text-[var(--tb-dropdown-hover-text)]"
                >
                  <Home className="w-3.5 h-3.5" />
                  Welcome Page
                </button>
              </div>
            )}
          </div>
        </div>

        {/* Separator */}
        <div className="w-px h-3.5 mx-1" style={{ background: 'var(--tb-separator)' }} />

        {/* Quick Action: Workspace & Browse All Songs View Toggles */}
        <div className="flex items-center gap-0.5">
          <Tooltip title="Main Workspace" placement="bottom">
            <button
              onClick={handleResolveToWorkspace}
              className={`w-7 h-7 flex items-center justify-center rounded-full transition-colors ${
                rightPanelView === "bento" && !isEditingSlide && !showSongEditor && !showNewSongModal
                  ? "text-blue-500 bg-[var(--tb-hover-bg)]"
                  : "hover:bg-[var(--tb-hover-bg)]"
              }`}
              style={
                rightPanelView !== "bento" || isEditingSlide || showSongEditor || showNewSongModal
                  ? { color: 'var(--tb-icon)' }
                  : undefined
              }
              aria-label="Main Workspace"
            >
              <Layers size={28} className="w-[28px] h-[28px]" strokeWidth={sw} />
            </button>
          </Tooltip>

          <Tooltip title="Browse All Songs" placement="bottom">
            <button
              onClick={() => dispatch(toggleAllSongsView())}
              className={`w-7 h-7 flex items-center justify-center rounded-full transition-colors ${
                rightPanelView === "allSongs"
                  ? "text-blue-500 bg-[var(--tb-hover-bg)]"
                  : "hover:bg-[var(--tb-hover-bg)]"
              }`}
              style={rightPanelView !== "allSongs" ? { color: 'var(--tb-icon)' } : undefined}
              aria-label="Browse All Songs"
            >
              <Music size={28} className="w-[28px] h-[28px]" strokeWidth={sw} />
            </button>
          </Tooltip>
        </div>
      </div>

      {/* ─── CENTER: Command Palette Search & Active Song Breadcrumb ─── */}
      <div
        className="flex-1 max-w-xl mx-2 flex items-center justify-center gap-2 min-w-0"
        style={{ WebkitAppRegion: "no-drag" } as React.CSSProperties}
      >
        {/* Central Search with Dropdown */}
        {isSongsScreen && (
          <div className="w-full max-w-sm">
            <SearchWithDropdown
              searchQuery={searchQuery}
              updateSearchQuery={updateSearchQuery}
              songs={songs}
              onPresent={presentSong}
              onDelete={showDeleteConfirmation}
              onSelectSong={(song) => {
                onSelectSongFromSearch(song);
                dispatch(setRightPanelView("bento"));
              }}
              isDarkMode={isDarkMode}
            />
          </div>
        )}

        {/* Staged Song & Slide Breadcrumb */}
        {isSongsScreen && (displayTitle || currentSlide) && (
          <div className="hidden lg:flex items-center gap-1.5 text-[11px] px-2 py-0.5 rounded-full max-w-[240px] flex-shrink-0 truncate" style={{ color: 'var(--tb-text)' } as React.CSSProperties}>
            {displayTitle && (
              <span className="font-medium truncate" style={{ color: 'var(--tb-text)' }} title={displayTitle}>
                {displayTitle}
              </span>
            )}
            {currentSlide && (
              <>
                <span style={{ color: 'var(--tb-text-muted)' }}>›</span>
                <span className={`font-semibold whitespace-nowrap ${isDarkMode ? "text-blue-400" : "text-blue-900"}`}>
                  {currentSlide.label}
                </span>
              </>
            )}
          </div>
        )}
      </div>

      {/* ─── RIGHT: Font Selector, Projection Controls, Status & Windows Controls ─── */}
      <div
        className="flex items-center gap-0.5 flex-shrink-0"
        style={{ WebkitAppRegion: "no-drag" } as React.CSSProperties}
      >
        {isSongsScreen && (
          <>
            {/* Font Family Selector */}
            <div className="relative" ref={fontDropdownRef}>
              <Tooltip title="Select Font Family" placement="bottom">
                <button
                  onClick={(e) => {
                    e.stopPropagation();
                    setShowFontDropdown(!showFontDropdown);
                  }}
                  className="h-7 px-2 rounded-md flex items-center gap-1.5 text-[11px] font-medium transition-colors hover:bg-[var(--tb-hover-bg)]"
                  style={{ background: showFontDropdown ? 'var(--tb-hover-bg)' : 'transparent', color: 'var(--tb-text)' } as React.CSSProperties}
                >
                  <span className="max-w-[85px] truncate">{selectedFont}</span>
                  <ChevronDown
                    className={`w-3 h-3 flex-shrink-0 transition-transform duration-200 ${showFontDropdown ? "rotate-180" : ""}`}
                    style={{ color: 'var(--tb-text-muted)' }}
                  />
                </button>
              </Tooltip>

              {showFontDropdown && (
                <div
                  className="absolute top-full right-0 mt-1 w-56 rounded-lg shadow-2xl z-[99999] flex flex-col overflow-hidden"
                  style={{ background: 'var(--tb-dropdown-bg)', border: '1px solid var(--tb-dropdown-border)' } as React.CSSProperties}
                >
                  <div className="px-2 py-1.5" style={{ borderBottom: '1px solid var(--tb-dropdown-border)' }}>
                    <input
                      ref={fontSearchInputRef}
                      type="text"
                      value={fontSearchQuery}
                      onChange={(e) => setFontSearchQuery(e.target.value)}
                      placeholder="Search fonts…"
                      className="w-full px-2 py-0.5 text-[11px] rounded focus:outline-none transition-colors"
                      style={{ background: 'var(--tb-input-bg)', color: 'var(--tb-text)', border: '1px solid var(--tb-dropdown-border)' } as React.CSSProperties}
                      onClick={(e) => e.stopPropagation()}
                      autoFocus
                    />
                  </div>

                  <div
                    ref={fontListRef}
                    className="overflow-y-auto no-scrollbar"
                    style={{ maxHeight: `${FONT_LIST_HEIGHT}px` }}
                    onScroll={(e) => setFontListScrollTop((e.currentTarget as HTMLDivElement).scrollTop)}
                  >
                    {fontsLoading ? (
                      /* Loading spinner while fonts are being fetched */
                      <div className="flex flex-col items-center justify-center py-10 gap-2.5" style={{ color: 'var(--tb-text-muted)' }}>
                        <LoaderCircle
                          className="w-5 h-5 animate-spin"
                          style={{ color: 'var(--tb-accent, #6366f1)' }}
                        />
                        <span className="text-[11px]">Loading fonts…</span>
                      </div>
                    ) : filteredFonts.length > 0 ? (
                      (() => {
                        const startIndex = Math.max(0, Math.floor(fontListScrollTop / FONT_ITEM_HEIGHT) - OVERSCAN);
                        const visibleCount = Math.ceil(FONT_LIST_HEIGHT / FONT_ITEM_HEIGHT) + OVERSCAN * 2;
                        const endIndex = Math.min(filteredFonts.length, startIndex + visibleCount);
                        const paddingTop = startIndex * FONT_ITEM_HEIGHT;
                        const paddingBottom = (filteredFonts.length - endIndex) * FONT_ITEM_HEIGHT;

                        return (
                          <>
                            <div style={{ height: paddingTop }} />
                            {filteredFonts.slice(startIndex, endIndex).map((font, relIdx) => {
                              const isActive = selectedFont === font;
                              const absIdx = startIndex + relIdx;
                              const isLast = absIdx === filteredFonts.length - 1;
                              return (
                                <button
                                  key={font}
                                  onClick={async () => {
                                    setSelectedFont(font);
                                    setShowFontDropdown(false);
                                    setFontSearchQuery("");
                                    dispatch(setFontFamily(font));
                                    localStorage.setItem("bmusicfontFamily", font);
                                    if (isProjectionActive) {
                                      try {
                                        await window.api.sendToSongProjection({
                                          type: "FONT_FAMILY_UPDATE",
                                          fontFamily: font,
                                        });
                                      } catch (e) {
                                        console.error("Error sending font update to projection:", e);
                                      }
                                    }
                                  }}
                                  className={`w-full flex items-center gap-2 px-2.5 text-left transition-colors group ${
                                    isActive
                                      ? "bg-[var(--tb-dropdown-active-bg)]"
                                      : "hover:bg-black/[0.04] dark:hover:bg-white/[0.05]"
                                  } ${
                                    !isLast ? "border-0 border-b border-dashed border-t-0 border-l-0 border-r-0 border-black/[0.15] dark:border-white/[0.10]" : ""
                                  }`}
                                  style={{
                                    height: `${FONT_ITEM_HEIGHT}px`,
                                    color: isActive ? 'var(--tb-dropdown-active-text)' : 'var(--tb-text)',
                                  }}
                                >
                                  {/* Checkmark — visible on active, faint on hover */}
                                  <div className={`w-3 h-3 flex items-center justify-center flex-shrink-0 transition-opacity ${
                                    isActive ? "opacity-100" : "opacity-0 group-hover:opacity-25"
                                  }`}>
                                    <Check className="w-2.5 h-2.5" />
                                  </div>
                                  {/* Font name rendered in its own typeface */}
                                  <span
                                    className={`truncate text-[11px] ${isActive ? "font-semibold" : ""}`}
                                    style={{ fontFamily: font }}
                                  >
                                    {font}
                                  </span>
                                </button>
                              );
                            })}
                            <div style={{ height: paddingBottom }} />
                          </>
                        );
                      })()
                    ) : (
                      <div className="px-3 py-3 text-center text-xs" style={{ color: 'var(--tb-text-muted)' }}>No fonts found</div>
                    )}
                  </div>
                </div>
              )}
            </div>

            {/* Live Radio Button */}
            {isProjectionActive && (
              <Tooltip title="Present Song Live" placement="bottom">
                <button
                  onClick={() => selectedSong && presentSong(selectedSong)}
                  disabled={!selectedSong}
                  className="w-7 h-7 flex items-center justify-center rounded-full transition-colors text-red-500 animate-pulse hover:bg-[var(--tb-hover-bg)]"
                >
                  <Radio size={28} className="w-[28px] h-[28px]" strokeWidth={sw} />
                </button>
              </Tooltip>
            )}

            {/* 5 Continuous Action Buttons: Project, Backup, Theme, Settings, Stats */}
            <div className="flex items-center -space-x-0.5">
              {/* Start / Stop Projection Toggle */}
              <Tooltip title={isProjectionActive ? "Stop Projection" : "Start Projection"} placement="bottom">
                <button
                  onClick={handleProjectionToggle}
                  disabled={!isProjectionActive && slides.length === 0}
                  className={`relative hover:z-10 w-7 h-7 flex items-center justify-center rounded-full transition-colors disabled:opacity-40 ${
                    isProjectionActive
                      ? `${isDarkMode ? "text-blue-400" : "text-blue-900"} hover:bg-[var(--tb-hover-bg)]`
                      : "hover:bg-[var(--tb-hover-bg)]"
                  }`}
                  style={!isProjectionActive ? { color: 'var(--tb-icon)' } : undefined}
                >
                  {isProjectionActive ? (
                    <MonitorStop size={28} className="w-[28px] h-[28px]" strokeWidth={sw} />
                  ) : (
                    <Monitor size={28} className="w-[28px] h-[28px]" strokeWidth={sw} />
                  )}
                </button>
              </Tooltip>

              {/* Backup Notification */}
              <BackupNotification />

              {/* Theme Toggle */}
              <ThemeToggle />

              {/* Settings */}
              <Tooltip title="Settings" placement="bottom">
                <button
                  onClick={() => dispatch(toggleSettings())}
                  className={`relative hover:z-10 w-7 h-7 flex items-center justify-center rounded-full transition-colors ${
                    rightPanelView === "settings"
                      ? "text-blue-500 bg-[var(--tb-hover-bg)]"
                      : "hover:bg-[var(--tb-hover-bg)]"
                  }`}
                  style={rightPanelView !== "settings" ? { color: 'var(--tb-icon)' } : undefined}
                >
                  <Settings size={28} className="w-[28px] h-[28px]" strokeWidth={sw} />
                </button>
              </Tooltip>

              {/* Statistics */}
              <Tooltip title="Statistics & History" placement="bottom">
                <button
                  onClick={() => dispatch(toggleStatistics())}
                  className={`relative hover:z-10 w-7 h-7 flex items-center justify-center rounded-full transition-colors ${
                    rightPanelView === "statistics"
                      ? "text-blue-500 bg-[var(--tb-hover-bg)]"
                      : "hover:bg-[var(--tb-hover-bg)]"
                  }`}
                  style={rightPanelView !== "statistics" ? { color: 'var(--tb-icon)' } : undefined}
                >
                  <BarChart3 size={28} className="w-[28px] h-[28px]" strokeWidth={sw} />
                </button>
              </Tooltip>
            </div>
          </>
        )}

        {/* Update Manager */}
        <UpdateManager />

        {/* Window controls divider */}
        <div className="w-px h-3.5 mx-0.5" style={{ background: 'var(--tb-separator)' }} />

        {/* Windows Control Buttons */}
        <div className="flex items-center gap-0.5">
          <button
            onClick={handleMinimize}
            className="w-7 h-7 flex items-center justify-center rounded-full transition-colors hover:bg-[var(--tb-hover-bg)]"
            style={{ color: 'var(--tb-icon)' }}
            title="Minimize"
          >
            <Minus size={24} className="w-[24px] h-[24px]" strokeWidth={sw} />
          </button>
          <button
            onClick={handleMaximize}
            className="w-7 h-7 flex items-center justify-center rounded-full transition-colors hover:bg-[var(--tb-hover-bg)]"
            style={{ color: 'var(--tb-icon)' }}
            title={isWindowMaximized ? "Restore" : "Maximize"}
          >
            {isWindowMaximized ? (
              <Copy size={24} className="w-[24px] h-[24px]" strokeWidth={sw} />
            ) : (
              <Square size={24} className="w-[24px] h-[24px]" strokeWidth={sw} />
            )}
          </button>
          <button
            onClick={handleClose}
            className="w-7 h-7 flex items-center justify-center rounded-full transition-colors hover:bg-red-600 hover:text-white"
            style={{ color: 'var(--tb-text)' }}
            title="Close"
          >
            <X size={24} className="w-[24px] h-[24px]" strokeWidth={sw} />
          </button>
        </div>
      </div>
    </div>
  );
};

export default TitleBar;
