import { useState, useEffect } from "react";
import { Minus, Maximize2, X, FileText, Home, User2 } from "lucide-react";

declare const __APP_VERSION__: string;
import UpdateManager from "./UpdateManager";

import { useAppSelector, useAppDispatch } from "@/store";
import {
  setCurrentScreen,
  setTheme,
  minimizeApp,
  maximizeApp,
  closeApp,
} from "@/store/slices/appSlice";
import { ThemeToggle } from "./ThemeToggler";
import { useTheme } from "@/Provider/Theme";

const TitleBar = () => {
  const [showDropdown, setShowDropdown] = useState<boolean>(false);

  const dispatch = useAppDispatch();
  const currentScreen = useAppSelector((state) => state.app.currentScreen);
  const theme = useAppSelector((state) => state.app.theme);
  const songTitle = useAppSelector((state) => state.songSlides.songTitle);
  const isAutoGeneratedTitle = useAppSelector(
    (state) => state.songSlides.isAutoGeneratedTitle,
  );
  const currentSlideId = useAppSelector(
    (state) => state.songSlides.currentSlideId,
  );
  const slides = useAppSelector((state) => state.songSlides.slides);
  // Get the selected song from Redux for language display
  const selectedSong = useAppSelector((state) => state.songs.selectedSong);
  const { isDarkMode, toggleDarkMode } = useTheme();

  // Get current slide info
  const currentSlide = slides.find((slide) => slide.id === currentSlideId);

  // Generate display title: only show if it's a saved/loaded title (not auto-generated)
  const getDisplayTitle = () => {
    // Only show title if it's from a saved/loaded song
    if (!isAutoGeneratedTitle && songTitle && songTitle.trim() !== "") {
      return songTitle;
    }

    return null;
  };

  const displayTitle = getDisplayTitle();

  // Hide title bar for presentation screens
  const shouldHideTitleBar = window.location.hash.includes(
    "presentation-display",
  );

  // Don't render title bar if it should be hidden
  if (shouldHideTitleBar) {
    return null;
  }

  useEffect(() => {
    const savedTheme = localStorage.getItem("bmusictheme");
    if (savedTheme) {
      dispatch(setTheme(savedTheme as any));
    }
  }, [dispatch]);

  // function to set theme choice for songs app
  const setThemeChoice = () => {
    const currentSongTheme = localStorage.getItem("bmusictheme") || "white";
    const newTheme = currentSongTheme === "creamy" ? "white" : "creamy";

    // Update localStorage
    localStorage.setItem("bmusictheme", newTheme);

    // Dispatch custom event to notify other components of the change
    window.dispatchEvent(
      new CustomEvent("localStorageChange", {
        detail: { key: "bmusictheme", newValue: newTheme },
      }),
    );
  };

  const randombgs = `rgba(${Math.floor(Math.random() * 255)},${Math.floor(
    Math.random() * 255,
  )},${Math.floor(Math.random() * 255)},0.6)`;

  const handleMinimize = () => {
    dispatch(minimizeApp());
  };

  const handleMaximize = () => {
    dispatch(maximizeApp());
  };

  const handleClose = () => {
    dispatch(closeApp());
  };
  const toggleDropdown = () => {
    setShowDropdown(!showDropdown);
  };

  const handleAddToPrelist = () => {
    // TODO: Implement add to prelist functionality
    console.log("Add to prelist clicked");
  };

  const selectedBg = isDarkMode ? "url('./wood10.jpg')" : "url(./wood10.jpg)";

  return (
    <div
      className="h-7  w-full fixed flex z-50 top-0 m-auto select-none"
      style={
        {
          WebkitAppRegion: "drag",
          backgroundImage: !isDarkMode
            ? `linear-gradient(to bottom,
             rgba(255, 255, 255, 0%) 0%,
             rgba(160, 160, 160, 1) 100%),
             ${selectedBg}`
            : `linear-gradient(to bottom,
             rgba(44, 44, 44, 0) 0%,
             #1c1c1c 80%),
              ${selectedBg}`,
          backgroundRepeat: "repeat",
          backgroundSize: !isDarkMode ? "30px" : "20px",
          backdropFilter: "blur(10px)",
          zIndex: 10,
        } as any
      }
    >
      <div className="flex w-full items-center justify-center px-1">
        <div
          className="flex items-center justify-between w-full"
          style={{ WebkitAppRegion: "no-drag" } as any}
        >
          {/* LEFT: logo + action buttons */}
          <div className="flex items-center gap-1">
            <img src="./evsongsicon.png" alt="icon" className="w-5 h-5 mr-1" />

            <button
              onClick={() => dispatch(setCurrentScreen("Home"))}
              className={`w-7 h-7 rounded flex items-center justify-center cursor-pointer transition-colors text-white/80 hover:text-white hover:bg-white/15 ${
                currentScreen === "Songs" ? "" : "hidden"
              }`}
              title="Home"
            >
              <Home className="w-5 h-5" />
            </button>

            <button
              onClick={() => dispatch(setCurrentScreen("userguide"))}
              className={`w-7 h-7 rounded flex items-center justify-center cursor-pointer transition-colors ${
                currentScreen !== "Songs" ? "hidden" : ""
              } ${
                currentScreen === "userguide"
                  ? "bg-white/20 text-white"
                  : "text-white/80 hover:text-white hover:bg-white/15"
              }`}
              title="User guide"
            >
              <User2 className="w-5 h-5" />
            </button>

            <ThemeToggle />

            {/* Song title + slide badge */}
            {currentScreen === "Songs" && (displayTitle || currentSlide) && (
              <div className="flex items-center gap-1.5 ml-1">
                {displayTitle && (
                  <div className="flex items-center gap-1.5 px-2 py-0.5 bg-white/10 rounded border border-white/15">
                    <FileText className="w-3 h-3 text-white/60 flex-shrink-0" />
                    <span className="text-[11px] font-medium text-white/80 max-w-[180px] truncate">
                      {displayTitle}
                    </span>
                  </div>
                )}
                {currentSlide && (
                  <div className="px-2 py-0.5 bg-white/15 rounded border border-white/20">
                    <span className="text-[11px] font-semibold text-white">
                      {currentSlide.label}
                    </span>
                  </div>
                )}
              </div>
            )}
          </div>

          {/* RIGHT: version pill + Windows-style window controls */}
          <div className="flex items-center gap-1 mr-1">
            <UpdateManager />
            <div className="w-px h-3.5 bg-white/15 mx-0.5" />
            <button
              onClick={handleMinimize}
              className="w-10 h-6 flex items-center justify-center text-white/70 hover:text-white bg-white/20 hover:bg-white/15 transition-colors"
              title="Minimize"
            >
              <Minus className="w-3.5 h-3.5" strokeWidth={2} />
            </button>
            <button
              onClick={handleMaximize}
              className="w-10 h-6 flex items-center justify-center text-white/70 hover:text-white bg-white/20 hover:bg-white/15 transition-colors"
              title="Maximize"
            >
              <Maximize2 className="w-3 h-3" strokeWidth={2} />
            </button>
            <button
              onClick={handleClose}
              className="w-10 h-6 flex items-center justify-center text-white/70 hover:text-white bg-red-500 hover:bg-red-500 transition-colors"
              title="Close"
            >
              <X className="w-3.5 h-3.5" strokeWidth={2} />
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};

export default TitleBar;
